input_channels: 768
output_channels: 768
encode_channels: 768
decode_channels: 768
code_dim: 768
codebook_num: 1
codebook_size: 1024
bias: true
enc_ratios: [ 1, 1 ]
dec_ratios: [ 1, 1 ]
enc_strides: [ 1, 1 ]  # no downsampling
dec_strides: [ 1, 1 ]
enc_kernel_size: 3
dec_kernel_size: 3
enc_block_dilations: [ 1, 1 ]
enc_block_kernel_size: 3
dec_block_dilations: [ 1, 1 ]
dec_block_kernel_size: 3